---
title: "AR process"
author: "Jiahao Tian"
date: "2023-04-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readr)
library(tumgr)
library(minpack.lm)
library(lubridate)

```


```{r}
DF1 = read_csv("~/Desktop/MS report/data/Data-selected/10083_IMQUAL_01Oct2021.csv")
DF2 = read_csv("~/Desktop/MS report/data/Data-selected/10083_TEXTCAD_01Oct2021.csv")
```


```{r}
d2 = DF1 %>% 
  dplyr:: select(contains("SUBJID",ignore.case = TRUE), 
                 contains("VISITDTN",ignore.case = TRUE),
                 contains("SLICE",ignore.case = TRUE))

qlf = DF2 %>% 
  dplyr:: select(contains("SUBJID",ignore.case = TRUE), 
                 contains("VISITDTN",ignore.case = TRUE),
                 contains("REGI",ignore.case = TRUE), 
                 contains("QLF",ignore.case = TRUE))
```


```{R}
d2$name = as.numeric(factor(d2$SUBJID, 
                  levels=unique(d2$SUBJID)))
qlf$name = as.numeric(factor(qlf$SUBJID, 
                  levels=unique(qlf$SUBJID)))

d2$SLICE_THICKNESS = as.numeric(d2$SLICE_THICKNESS)
d2$SLICE_SPACING = as.numeric(d2$SLICE_SPACING)

qlf = qlf[grep("WHOLE", qlf$REGION), , drop = FALSE]
```


```{r}
d2$size = d2$SLICE_THICKNESS * d2$SLICE_SPACING 

qlf$size = (qlf$QLFCAD * 5014) / 100
```


```{r}  
lapply(d2, function(x) {length(which(is.na(x)))})
lapply(qlf, function(x) {length(which(is.na(x)))})
d2 = na.omit(d2)
```


```{r}
d2$date = strptime(d2$VISITDTN, "%d%b%Y")

qlf$date = strptime(qlf$VISITDTN, "%d%b%Y")
```

```{r}
d2 = d2 %>% 
  dplyr:: select(contains("date",ignore.case = TRUE), 
                 contains("name",ignore.case = TRUE),
                 contains("size",ignore.case = TRUE))

qlf = qlf %>% 
  dplyr:: select(contains("date",ignore.case = TRUE), 
                 contains("name",ignore.case = TRUE),
                 contains("size",ignore.case = TRUE))

```


```{r}
# assuming your data is in a data frame called "my_data" with columns "patient", "date", and "value"
# sort the data by patient and date
my_data <- qlf[order(qlf$name, qlf$date),]

# create a time series object with patient as the time index and value as the data
my_ts <- ts(qlf$size, start = c(1, 1), frequency = length(unique(qlf$name)))

# difference the time series to achieve stationarity
my_diff <- diff(my_ts)

# fit an AR model to the differenced data
library(forecast)
my_ar <- auto.arima(my_diff)


```


####################################

```{r}
plot(my_ar$var.coef)

```