---
title: "Untitled"
author: "Jiahao Tian"
date: "2023-04-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
set.seed(55)
hh = hc(treat1, modelName = "EEE")
hc <- hclass(hh)

par(mfrow = c(2, 2))
plot(treat1, col = hc[, 1])
plot(treat1, col = hc[, 2])
plot(treat1, col = hc[, 3])
plot(treat1, col = hc[, 4])
```


```{r}
mclustBIC(hh)

mclustBIC(hc)


```


```{r}
plot(treat1[, 1:3], cex = 4, col = hc[, 3])
text(treat1[, 1], treat1[, 3], LETTERS)
```
```{r}
# Create separate data frames for each cluster
cluster_membership = hc[,3]

num_clusters = max(cluster_membership)
cluster_data = list()
for (i in 1:num_clusters) {
  cluster_data[[i]] = treat1[cluster_membership == i, ]
  cat("Cluster", i, "has", nrow(cluster_data[[i]]), "members.\n")
}
```
```{r}

clusters = hc[,3]  # Cluster labels for each data point

# Create new datasets for each cluster
data_cluster1 = treat1[clusters == 1, ]
data_cluster2 = treat1[clusters == 2, ]
data_cluster3 = treat1[clusters == 3, ]
data_cluster4 = treat1[clusters == 4, ]

# Print the number of subjects in each cluster
cat("Number of data points in Cluster 1:", nrow(data_cluster1), "\n")
cat("Number of data points in Cluster 2:", nrow(data_cluster2), "\n")
cat("Number of data points in Cluster 3:", nrow(data_cluster3), "\n")
cat("Number of data points in Cluster 4:", nrow(data_cluster4), "\n")
```

```{r}

fviz_mclust(hh, "classification") 


```


```{r}



```