---
title: "treatment combination g-d-model"
author: "Jiahao Tian"
date: "2023-04-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(readr)
library(tumgr)
library(minpack.lm)
library(survival)
library(survminer)
library(grid)
```

```{r}
## read data

DF1 = read.table(
  "~/Desktop/MS report/data/Data-selected/10083_IMQUAL_01Oct2021.csv", 
  sep = ",", header = TRUE)

DF2 = read.table(
  "~/Desktop/MS report/data/Data-selected/10083_TEXTCAD_01Oct2021.csv",
  sep = ",", header = TRUE)


## extract needed variables for model

d2 = DF1 %>% 
  dplyr:: select(contains("SUBJID",ignore.case = TRUE), 
                 contains("VISITDTN",ignore.case = TRUE),
                 contains("SLICE",ignore.case = TRUE))

qlf = DF2 %>% 
  dplyr:: select(contains("SUBJID",ignore.case = TRUE), 
                 contains("VISITDTN",ignore.case = TRUE),
                 contains("REGI",ignore.case = TRUE), 
                 contains("QLF",ignore.case = TRUE))

## change variable type

d2$name = as.numeric(factor(d2$SUBJID, 
                  levels=unique(d2$SUBJID)))
qlf$name = as.numeric(factor(qlf$SUBJID, 
                  levels=unique(qlf$SUBJID)))

d2$SLICE_THICKNESS = as.numeric(d2$SLICE_THICKNESS)
d2$SLICE_SPACING = as.numeric(d2$SLICE_SPACING)

# only use whole lung data for g-d-rate model

qlf = qlf[grep("WHOLE", qlf$REGION), , drop = FALSE]

## change to 2d dim 
## change name to size due to model requirment

d2$size = d2$SLICE_THICKNESS * d2$SLICE_SPACING 
qlf$size = qlf$QLFCAD
```

```{r}
## change time to day due model requirement

d2$date = as.Date(d2$VISITDTN, format = "%d%b%Y")
d2$date = as.numeric(d2$date)

qlf$date = as.Date(qlf$VISITDTN, format = "%d%b%Y")
qlf$date = as.numeric(qlf$date)


## extract needed variables for model

d2 = d2 %>% 
  dplyr:: select(contains("name",ignore.case = TRUE), 
                 contains("date",ignore.case = TRUE),
                 contains("size",ignore.case = TRUE))

qlf = qlf %>% 
  dplyr:: select(contains("name",ignore.case = TRUE), 
                 contains("date",ignore.case = TRUE),
                 contains("size",ignore.case = TRUE))


## change to dataframe fro model use

d2 = as.data.frame(d2)
qlf = as.data.frame(qlf)

## check and delet missing value

lapply(d2, function(x) {length(which(is.na(x)))})
lapply(qlf, function(x) {length(which(is.na(x)))})
d2 = na.omit(d2)


## run model

out1 = gdrate(d2, 0.05, FALSE)
out2 = gdrate(qlf, 0.05, FALSE)

out1$models
out2$models

out1$results
out2$results
```

```{r}
## read data

DF1 = read.table(
  "~/Desktop/MS report/data/Data-selected/10083_IMQUAL_01Oct2021.csv", 
  sep = ",", header = TRUE)

DF2 = read.table(
  "~/Desktop/MS report/data/Data-selected/10083_TEXTCAD_01Oct2021.csv",
  sep = ",", header = TRUE)

treat = read.table(
  "~/Desktop/MS report/data/Data-selected 2/IIMQILD_221104_Box.csv", 
  sep = ",", header = TRUE)

## change column name for merge
colnames(treat)[which(names(treat) == "Patient_ID")] = "SUBJID"


##merge
DF1_merge = merge(DF1, treat, by = 'SUBJID', all = TRUE)
DF2_merge = merge(DF2, treat, by = 'SUBJID', all = TRUE)


##extract needed variables

d2_treat = DF1_merge %>% 
  dplyr:: select(Age,
                 V1_WL_QLF,
                 V1_WL_QILD,
                 contains("SUBJID",ignore.case = FALSE), 
                 contains("VISITDTN",ignore.case = FALSE),
                 contains("Sex",ignore.case = FALSE),
                 contains("V1_CTdate",ignore.case = FALSE),
                 contains("V2_CTdate",ignore.case = FALSE),
                 contains("V3_CTdate",ignore.case = FALSE),
                 contains("V1V2",ignore.case = FALSE),
                 contains("V1V3",ignore.case = FALSE),
                 contains("SLICE",ignore.case = FALSE))

qlf_treat = DF2_merge %>% 
  dplyr:: select(Age,
                 V1_WL_QLF,
                 V2_WL_QLF,
                 V3_WL_QLF,
                 V1_WL_QILD,
                 V2_WL_QILD,
                 V3_WL_QILD,
                 QLFCAD,
                 QILD,
                 FUloss,
                 Death,
                 contains("SUBJID",ignore.case = FALSE), 
                 contains("VISITDTN",ignore.case = FALSE),
                 contains("Sex",ignore.case = FALSE),
                 contains("V1_CTdate",ignore.case = FALSE),
                 contains("V2_CTdate",ignore.case = FALSE),
                 contains("V3_CTdate",ignore.case = FALSE),
                 contains("V1V2",ignore.case = FALSE),
                 contains("V1V3",ignore.case = FALSE),
                 contains("REGI",ignore.case = FALSE))

## only need whole lung data
qlf_treat = qlf_treat[grep("WHOLE", qlf_treat$REGION), , drop = FALSE]


## change variable type


qlf_treat$name = as.numeric(factor(qlf_treat$SUBJID, 
                  levels=unique(qlf_treat$SUBJID)))

## check and delet missing value

#lapply(d2, function(x) {length(which(is.na(x)))})
#lapply(qlf, function(x) {length(which(is.na(x)))})
#d2 = na.omit(d2)




qlf_treat = as.data.frame(qlf_treat)
```


```{r}
get_treatment_combinations = function(df, dichotomous_vars, new_col_name) {
  
  # create a new column with treatment information
  df[[new_col_name]] = apply(df[dichotomous_vars], 1, function(x) {
    treatments = names(x[x == 1])
    if (length(treatments) == 0) {
      "None"
    } else if (length(treatments) == 1) {
      treatments
    } else {
      paste(treatments, collapse = "+")
    }
  })
  
  # return the modified dataframe
  return(df)
}

```

```{R}
# List of dichotomous variables
dichotomous_vars = c("HiPD_V1V2", "CsA_V1V2", "CTX_V1V2","AZT_V1V2", 
                      "Tac_V1V2", "MMF_V1V2", "MTX_V1V2", "IVIg_V1V2",
                      "RTX_V1V2", "ISswitch_V1V2")

qlf1 = get_treatment_combinations(qlf_treat, dichotomous_vars, "treat_comb_V1V2")


dichotomous_vars2 = c("HiPD_V1V3", "CsA_V1V3", "CTX_V1V3","AZT_V1V3", 
                      "Tac_V1V3", "MMF_V1V3", "MTX_V1V3", "IVIg_V1V3",
                      "RTX_V1V3", "ISswitch_V1V3")

qlf1 = get_treatment_combinations(qlf1, dichotomous_vars2, "treat_comb_V1V3")
```


```{r}
cols_to_select = c("type", "selectedFit", "name", "g", "d", "phi")

gd1 = as.data.frame(out2$results[cols_to_select])

qlf1 = merge(qlf1, gd1, by = "name", all = TRUE)
```


```{r}
g_d_rank = qlf1 %>% 
  dplyr:: select(Age,
                 V1_WL_QLF,
                 V2_WL_QLF,
                 V3_WL_QLF,
                 contains("Sex",ignore.case = FALSE),
                 contains("V1_CTdate",ignore.case = FALSE),
                 contains("V2_CTdate",ignore.case = FALSE),
                 contains("V3_CTdate",ignore.case = FALSE),
                 FUloss,
                 Death,
                 SUBJID,
                 name,
                 treat_comb_V1V2,
                 treat_comb_V1V3,
                 g,
                 d,
                 phi,
                 type,
                 selectedFit)

g_d_rank = distinct(g_d_rank)
```

```{R}
#write.csv(g_d_rank,"treat_combine.csv", row.names = TRUE)
```


```{r}

# subset data into two groups
df_d_only = select(g_d_rank, -g)
df_g_only = select(g_d_rank, -d)

df_g_only = df_g_only %>% 
  dplyr:: select(treat_comb_V1V2,
                 treat_comb_V1V3,
                 g,
                 phi,
                 selectedFit,
                 type,
                 Age,
                 SUBJID,
                 name,
                 Sex,
                 FUloss,
                 Death) %>%
  arrange(is.na(g), g)

df_d_only = df_d_only %>% 
   dplyr:: select(treat_comb_V1V2,
                 treat_comb_V1V3,
                 d,
                 phi,
                 selectedFit,
                 type,
                 Age,
                 SUBJID,
                 name,
                 Sex,
                 FUloss,
                 Death) %>%
  arrange(desc(d))

```


```{R}
write.csv(g_d_rank,"treat_combine.csv", row.names = TRUE)
write.csv(df_g_only,"g-rate-only.csv", row.names = TRUE)
write.csv(df_d_only,"d-rate-only.csv", row.names = TRUE)

```


######### Survival Curve

```{r}
qlf1$date = as.Date(qlf1$VISITDTN, format = "%d%b%Y")
qlf1$date = as.numeric(qlf1$date)

```

```{r}
# Calculate the percent  change of QLF score

qlf1$visitdate = as.Date(qlf1$VISITDTN, format = "%d%b%Y")

# Calculate the initial and final tumor size for each patient
initial_sizes = qlf1 %>%
  group_by(name) %>%
  summarize(initial_size = min(QLFCAD[visitdate == min(visitdate)]))

final_sizes = qlf1 %>%
  group_by(name) %>%
  summarize(final_size = max(QLFCAD[visitdate == max(visitdate)]))

# Merge the initial and final tumor sizes
size_changes = merge(initial_sizes, final_sizes, by = "name")


# Calculate the percent change for each patient
size_changes$change = (size_changes$final_size - size_changes$initial_size) 

# Display the percent change for each patient
print(size_changes)
```


```{r}
df = read.csv("treat_combine.csv", sep = ",", header = TRUE)

df = merge(df, size_changes, by = 'name', all = TRUE)

write.csv(df,"treat_combine.csv", row.names = TRUE)


```



```{r}
# Sort data by patient ID and visit date
qlf12 = qlf1[order(qlf1$name, qlf1$date),]

# Calculate total follow-up time in days
total_follow_up_days = aggregate(date ~ name, qlf12, function(x) max(x) - min(x))
colnames(total_follow_up_days)[which(names(total_follow_up_days) == "date")] = "fu_date"
```

```{r}
qlf111 = merge(df_g_only, total_follow_up_days, by = 'name', all = TRUE)
qlf222 = merge(df_d_only, total_follow_up_days, by = 'name', all = TRUE)
g_d_rank = merge(g_d_rank, total_follow_up_days, by = 'name', all = TRUE)
g_d_rank$time_mon = g_d_rank$fu_date / 30



#sur_df1 = sur_df1[!is.na(sur_df1$date) & !is.na(sur_df1$g), ]

qlf111 = qlf111[!is.na(qlf111$fu_date) & !is.na(qlf111$g), ]
qlf111$time_mon = qlf111$fu_date / 30

qlf222 = qlf222[!is.na(qlf222$fu_date) & !is.na(qlf222$d), ]
qlf222$time_mon = qlf222$fu_date / 30

qlf111$Number1 <- match(qlf111$treat_comb_V1V2, unique(qlf111$treat_comb_V1V2))
qlf111$Number2 <- match(qlf111$treat_comb_V1V3, unique(qlf111$treat_comb_V1V3))

qlf222$Number1 <- match(qlf222$treat_comb_V1V2, unique(qlf222$treat_comb_V1V2))
qlf222$Number2 <- match(qlf222$treat_comb_V1V3, unique(qlf222$treat_comb_V1V3))


```

```{r}
## chose threshold

#sur_df$g = log(sur_df$g)
qlf111$log_g = log(qlf111$g)
qlf222$log_d = log(qlf222$d)




hist(qlf111$log_g, main = "Tumor Growth Rate Distribution", xlab = "Tumor Growth Rate", col = "lightblue", border = "black")

mean_growth_rate = mean(qlf111$log_g)
median_growth_rate = median(qlf111$log_g)
quantiles_growth_rate = quantile(qlf111$log_g, probs = c(0.25, 0.5, 0.75))

print(mean_growth_rate)
print(median_growth_rate)
print(quantiles_growth_rate)

hist(qlf222$log_d, main = "Tumor Decay Rate Distribution", xlab = "Tumor Growth Rate", col = "lightblue", border = "black")

mean(qlf222$log_d)
median(qlf222$log_d)
quantile(qlf222$log_d, probs = c(0.25, 0.5, 0.75))

```

```{r}
# Replace 'chosen_threshold' with the threshold value you decided on
### NO NEED!!!!!! no meaning!!!!
chosen_threshold = -7.233721
chosen_threshold1 = -6.492849



qlf111$event = ifelse(qlf111$log_g > chosen_threshold, 1, 0)
qlf222$event = ifelse(qlf222$log_d > chosen_threshold, 1, 0)
```

```{r}

# Create a subset
surv_obj = Surv(qlf111$time_mon, qlf111$Death)

# Fit the Kaplan-Meier model for the subset
km_fit = survfit(surv_obj ~ qlf111$Number1)


# Plot the Kaplan-Meier curve for the subset
g_landmark = ggsurvplot(km_fit, data = qlf111, risk.table = TRUE, pval = TRUE)
g_landmark
#plot(km_fit, log = "x", xlab = "Time (log scale)", ylab = "Survival probability")


survdiff(surv_obj ~ qlf111$Number1)



```



```{r}
# Subset the data to observations beyond the landmark time
landmark_time = #idk
landmark_data = qlf111[qlf111$time_mon > landmark_time, ]

# Create the subset
landmark_surv_obj = Surv(landmark_data$time_mon, landmark_data$event)

# Fit the Kaplan-Meier model for the subset
landmark_km_fit = survfit(landmark_surv_obj ~ 1)

# Plot the Kaplan-Meier curve for the subset
g_landmark = ggsurvplot(landmark_km_fit, data = landmark_data, risk.table = TRUE, pval = TRUE)
g_landmark

plot(landmark_km_fit, log = "x", xlab = "Time (log scale)", ylab = "Survival probability")
```


```{R}

# Calculate the tertiles of the log growth rate
log_growth_tertiles = quantile(qlf111$log_g, probs = c(1/3, 2/3))

# Create a new column with the tertile groups
qlf111$log_growth_tertile = cut(qlf111$log_g,
                                  breaks = c(-Inf, log_growth_tertiles, Inf),
                                  labels = c("1", "2", "3"),
                                  include.lowest = TRUE)


# Calculate the tertiles of the log decay rate
log_decay_tertiles = quantile(qlf222$log_d, probs = c(1/3, 2/3))

# Create a new column with the tertile groups
qlf222$log_decay_tertile = cut(qlf222$log_d,
                                  breaks = c(-Inf, log_decay_tertiles, Inf),
                                  labels = c("1", "2", "3"),
                                  include.lowest = TRUE)



```


```{r}
landmark_surv_obj = Surv(qlf111$time_mon, qlf111$Death)

# Fit the Kaplan-Meier model for the subset
landmark_km_fit = survfit(landmark_surv_obj ~ qlf111$log_growth_tertile)

# Plot the Kaplan-Meier curve for the subset
g_landmark = ggsurvplot(landmark_km_fit, data = qlf111, risk.table = TRUE, pval = TRUE)
g_landmark

plot(landmark_km_fit, log = "x", xlab = "Time (log scale)", ylab = "Survival probability")

landmark_surv_obj1 = Surv(qlf222$time_mon, qlf222$Death)

# Fit the Kaplan-Meier model for the subset
landmark_km_fit1 = survfit(landmark_surv_obj1 ~ qlf222$log_decay_tertile)

# Plot the Kaplan-Meier curve for the subset
g_landmark1 = ggsurvplot(landmark_km_fit1, data = qlf222, risk.table = TRUE, pval = TRUE)
g_landmark1

plot(landmark_km_fit1, log = "x", xlab = "Time (log scale)", ylab = "Survival probability")


```

```{r}

table(g_d_rank$selectedFit)
table(g_d_rank$treat_comb_V1V2)
```
